apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-deployment
spec:
  selector:
    matchLabels:
      app: tf
  template:
    metadata:
      name: tf-container
      labels:
        app: tf
    spec:
      volumes:
        - name: src
          hostPath:
            path: /mnt/src
            type: Directory
      containers:
      - name: tf
        image: tensorflow/tensorflow:nightly-py3-jupyter
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
        volumeMounts:
          - name: src
            mountPath: /tf/src
