apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildbot-deployment
spec:
  selector:
    matchLabels:
      app: buildbot
  template:
    metadata:
      labels:
        app: buildbot
    spec:
      containers:
      - name: buildbot
        image: hp_build_bot:1.0.0.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
