# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.hostname = "TestVM1"
    master.vm.network "public_network", ip: "10.0.2.10"
    # modify mem, cpu
    config.vm.provider "virtualbox" do |v|
      v.cpu = 2
      v.memory = 2048
    end
  end
end